DO $$
BEGIN
    SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'scraper') THEN
        CREATE ROLE scraper WITH LOGIN PASSWORD '12345678' SUPERUSER;
    END IF;
END $$;
